services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  airflow:
    build:
      context: ./
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8000:8080"
    command: airflow standalone
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:admin@postgres/postgres
    depends_on:
      - postgres